"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

# from setuptools import setup
# 
# APP = ['src/Program_Start.py']
# DATA_FILES = ['--iconfile', 'src/Program/seagate_logo.ico']
# OPTIONS = {'argv_emulation': True}
# 
# setup(
#     app=APP,
#     data_files=DATA_FILES,
#     options={'py2app': OPTIONS},
#     setup_requires=['py2app'],
# )

#---------------------------------------

import sys
import os

from setuptools import setup

__version__ = '0.5.1'

def pathProgram():
    """
    Return the working path of the program in string.
    """
    FILEPATH=os.path.abspath(sys.argv[0])
    DIRPATH=os.path.dirname(FILEPATH)
    return str(DIRPATH)

program_entry = 'Program_Start.py'
program_entry_path = os.path.join(pathProgram(),'release','Program_Start.py')
# icon_path = os.path.join(pathProgram(), "release", "Program", "seagate_logo.ico")
# icon_path = 'src/Program/seagate_logo.ico'

APP = [program_entry_path]
DATA_FILES = []

OPTIONS = {
           'argv_emulation': True,
#            'iconfile': icon_path,
           'plist': {'CFBundleShortVersionString':'0.1.0',}
           }

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)


